### ISSUE TITLE
where can i get "train img list"?

### ISSUE THREAD

**Issue by dolphin0104** [KeqiangSun/FAB#7]
Hi Thanks for your work.
But, where can i get the img list?
"data/300VW/labels_68pt_256_train_sorted.txt"?

**Comment by MamonaAwan** [comment]
Hi, same issue. Where is this 300VW/labels_68pt_256_train_sorted.txt file? Thanks

**Comment by MamonaAwan** [comment]
Hi, same issue. Where can I get this labels_68pt_256_train_sorted.text file? Thanks
